### ISSUE TITLE
If an assembly is added/removed multiple times there is duplicated prebuild steps

### ISSUE THREAD

**Issue by wegged** [urasandesu/Prig#36]

**Comment by urasandesu** [comment]
That's certainly inconvenient. I'm going to correct this issue, too.

Until now, I was removing manually if added wrong settings as described in [this page](https://github.com/urasandesu/Prig.V2Docs/wiki/Sealed-Mocking-by-Telerik-JustMock). Because (I forgot the reason) I believed that it is impossible to recognize the content of `PreBuildEvent` tag in csproj :pensive:

Probably, it will be achieved by just matching the indirection stub setting name(e.g. `mscorlib.v4.0.30319.v4.0.0.0.prig`).
