### ISSUE TITLE
Suggestion add prig files as Copy If Newer to output directory

### ISSUE THREAD

**Issue by wegged** [urasandesu/Prig#37]
Suggestion add prig files as Copy If Newer to output directory, so that it forces a build even if there were no code changes aside from the prig settings.

**Comment by urasandesu** [comment]
My understanding is that Prig builds relevant files forcibly and copies them to output directory if the following operations are performed; Otherwise do nothing: 
* When the relevant files of Prig have not been existed in the output directory yet.
* When rebuilding.
* When modifying the indirection settings after the latest output.

Are the above points right?

**Comment by wegged** [comment]
You are correct I must have missed something when I was experiencing this sorry about that.

**Comment by urasandesu** [comment]
Thanks for your response!
I want to handle your suggestion on this issue, so I've reopened. Please be understanding of that :wink:

**Comment by urasandesu** [comment]
Fixed at https://github.com/urasandesu/Prig/releases/tag/v2.0.0-alpha04
