### ISSUE TITLE
Test engine crashes while trying to execute a unit test without indirections context even when it doesn't use any stubs

### ISSUE THREAD

**Issue by korzenikov** [urasandesu/Prig#40]
Hi,
I have a project with two unit tests - one of them uses a stub for DateTime.Now, the other one uses unstubbed DateTime.Now:

    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void UseDateTimeWithoutStubs()
        {
            var dateTime = DateTime.Now;
        }

        [TestMethod]
        public void UseDateTimeWithStubs()
        {
            using (new IndirectionsContext())
            {
                PDateTime.NowGet().Body = () => new DateTime(2013, 12, 13, 11, 00, 00);
                var dateTime = DateTime.Now;
            }
        }
    }

Surprisingly,while the first test doesn't use any stubs at all, it makes execution engine crash. The issue is resolved if I use IndirectionsContext in this test, but it looks a little bit strange why a test that doesn't use Prig Stubs should use IndirectionsContext.

**Comment by urasandesu** [comment]
Thank you for reporting issue! :kissing_heart:

This problem seems possible to reproduce in my environment. When the crash was occurred, I found the following error in my environment Event Viewer: 
![untitled](https://cloud.githubusercontent.com/assets/291065/7213476/1787bb50-e5bb-11e4-8337-5d0f8b66d045.png)

```
Faulting application name: vstest.executionengine.exe, version: 12.0.30501.0, time stamp: 0x5361ead0
Faulting module name: clr.dll, version: 4.0.30319.34014, time stamp: 0x52e0b86c
Exception code: 0xc0000005
Fault offset: 0x0000000000099808
Faulting process id: 0xf6c
Faulting application start time: 0x01d0797b601051a8
Faulting application path: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: a3bfafe7-e56e-11e4-8277-000d3a501d07
Faulting package full name: 
Faulting package-relative application ID: 
```

Is these errors same as your environment?

**Comment by korzenikov** [comment]
Yes, while my error message slightly differs from yours one, in general it is the same:

Faulting application name: vstest.executionengine.exe, version: 12.0.30501.0, time stamp: 0x5361ead0
Faulting module name: clr.dll, version: 4.0.30319.18444, time stamp: 0x52717f9a
Exception code: 0xc0000005
Fault offset: 0x000000000006470c
Faulting process id: 0x1ce4
Faulting application start time: 0x01d079811ca052fd
Faulting application path: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 5e1a3b17-e574-11e4-b48c-005056821e72

**Comment by urasandesu** [comment]
OK, this issue is probably caused same as #33 :disappointed_relieved:

In my environment, the error was gone after using [local build *.nupkg](https://drive.google.com/open?id=0B4s_gXgDJAgbRDljMF9WLTNzcFU&authuser=0) and performing [some manual steps](https://github.com/urasandesu/Prig/issues/32#issuecomment-89479093). If you are in a hurry, you can resolve the issue by same steps.

**Comment by urasandesu** [comment]
Fixed at https://github.com/urasandesu/Prig/releases/tag/v2.0.0-alpha04
