### ISSUE TITLE
Version 2.0.0 not showing up via Nuget.org

### ISSUE THREAD

**Issue by abbeycode** [urasandesu/Prig#50]
v1.1.1 is showing as the latest. When will 2.0.0 be added?

**Comment by abbeycode** [comment]
It also looks like Chocolatey only has 2.0.0-alpha06

**Comment by urasandesu** [comment]
The latest version is [2.0.0 in Chocolatey](https://chocolatey.org/packages/Prig/2.0.0). It is under the package moderation, but it can work completely. To install it, you have to specify the `-version` parameter explicitly. Also, it seems that you have already installed alpha version. I recommend uninstalling it before that.

In conclusion, you have only to execute the following commands in the PowerShell that runs as Administrator: 
```powershell
PS> choco uninstall prig -y -f
PS> choco install prig -version 2.0.0 -y
```

**Comment by abbeycode** [comment]
Had NuGet.org been deprecated in favor of Chocolatey?

**Comment by urasandesu** [comment]
No, I don't like Chocolatey very much because it has too heavy moderation procedure :persevere: 
However, there was technical limitation of NuGet to support Visual Studio integrated environment.

**Comment by abbeycode** [comment]
Will 2.0.0 eventually be released on NuGet?

**Comment by urasandesu** [comment]
At the moment, it won't. Because NuGet doesn't have enough functions to manage Prig 2.0.0. For example, extend the context menu, hook the build event and so on.

By the way, I'm working on issue #49, and I'm planning to distribute this library in Visual Studio Gallery. I think that you will be able to install easy as same as NuGet if it is finished.
