### ISSUE TITLE
Unable to get Prig Indirectection Stub Settings from ILSpy for 3rd Party Dll

### ISSUE THREAD

**Issue by jaisondoss** [urasandesu/Prig#70]
Am unable to get Indirection Stub settings from ILSpy due to below error:

![error](https://cloud.githubusercontent.com/assets/18750348/15013972/a8799538-1220-11e6-823c-6ec266f07d19.jpg)

**Comment by urasandesu** [comment]
It seems that ILSpy.GetPrigIndirectionStubSetting.Plugin can't resolve the referenced assembly. However, it is strange... :confused: 
Because ILSpy will resolve the dependency automatically. For example, there is the `ClassLibrary51Class1.Foo` method that has one parameter of `ClassLibrary5Class1` type. The type is in the referenced assembly. When you clicked the method to perform `Get Prig Indirection Stub Setting`, ILSpy should load the dependency automatically: 
![untitled](https://cloud.githubusercontent.com/assets/291065/15033551/be0a72ba-12a6-11e6-9aa5-c1069ebf0653.png)

Could you tell me more details how to you perform `Get Prig Indirection Stub Setting`? For example: 
* The member that you performed `Get Prig Indirection Stub Setting`
* The assembly that the member belongs
* The directory location of the assembly
* Whether the directory contains dependent assemblies

**Comment by jaisondoss** [comment]
Unblocking the dlls from local machine resolved the issue.
![image](https://cloud.githubusercontent.com/assets/18750348/15054882/52cac212-1327-11e6-9823-b18e1b881d90.png)

**Comment by urasandesu** [comment]
Oh, I didn't notice that :fearful: I should describe that in [its document](https://github.com/urasandesu/ILSpy.GetPrigIndirectionStubSetting.Plugin/blob/c3fab30043b9fee4c70b1633cc58758620398d3e/README.md), shouldn't I? Thanks for telling me the way to correct!!
