### ISSUE TITLE
Could Prig auto-generate delegate types?

### ISSUE THREAD

**Issue by poizan42** [urasandesu/Prig#82]
Currently you have to manually add delegate types if you have method signatures that doesn't match any of the predefined delegates. Since Prig autogenerates code anyways couldn't it just automatically generate whatever delegate types that are necessary?

**Comment by urasandesu** [comment]
I can't understand what you want, sorry... 
* If the timing of auto-generation that you say is runtime or compile time, how are you going to write the test without delegate?
* If the timing is before the above, what kind of image do you have of user operation?

By the way, about the former, I have already known that [JustMock has such API](http://www.telerik.com/products/mocking.aspx#intuitive-api-with-better-discoverability). However, I think that the way is not good because it is not type-safe against the non-public method.
